externals: {}
profile: humanitec/default-module
spec:
  containers:
    productcatalogservice:
      files: {}
      image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.6.0
      liveness_probe:
        command:
          - /bin/grpc_health_probe
          - '-addr=:3550'
        type: command
      readiness_probe:
        command:
          - /bin/grpc_health_probe
          - '-addr=:3550'
        type: command
      resources:
        limits:
          cpu: '0.250'
          memory: 256Mi
        requests:
          cpu: '0.025'
          memory: 64Mi
      variables:
        DISABLE_PROFILER: '1'
        PORT: '3550'
      volume_mounts: {}
  service:
    ports:
      grpc:
        container_port: 3550
        protocol: TCP
        service_port: 3550
