apiVersion: core.api.humanitec.io/v1
kind: Definition
metadata:
  id: redis-in-cluster
object:
  name: redis-in-cluster
  type: redis
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |-
          name: redis
          port: 6379
        manifests: |-
          deployment.yaml:
            location: namespace
            data:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: {{ .init.name }}
              spec:
                selector:
                  matchLabels:
                    app: {{ .init.name }}
                template:
                  metadata:
                    labels:
                      app: {{ .init.name }}
                  spec:
                    securityContext:
                      fsGroup: 1000
                      runAsGroup: 1000
                      runAsNonRoot: true
                      runAsUser: 1000
                      seccompProfile:
                        type: RuntimeDefault
                    containers:
                    - name: {{ .init.name }}
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                        privileged: false
                        readOnlyRootFilesystem: true
                      image: redis:alpine
                      ports:
                      - containerPort: {{ .init.port }}
                      volumeMounts:
                      - mountPath: /data
                        name: redis-data
                    volumes:
                    - name: redis-data
                      emptyDir: {}
          service.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: Service
              metadata:
                name: {{ .init.name }}
              spec:
                type: ClusterIP
                selector:
                  app: {{ .init.name }}
                ports:
                - name: tcp-redis
                  port: {{ .init.port }}
                  targetPort: {{ .init.port }}
        outputs: |
          host: {{ .init.name }}
          port: {{ .init.port }}
  criteria:
    - {}