name: Pull Request
on:
  pull_request:
    types:
      - closed
jobs:
  ob-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Humanitec App
        run: |
            curl -X DELETE \
            -H "Content-Type: application/json" \
            -H 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            https://api.humanitec.io/orgs/${{ vars.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}/envs/pr-${{ github.event.number }}
