name: Pull Request
on:
  pull_request:
    paths:
      - 'samples/onlineboutique/frontend/**'
      - '.github/workflows/ob-frontend-pr.yaml'
    types:
      - closed
jobs:
  ob-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete Humanitec Env
        env:
          HUMANITEC_ORG: ${{ secrets.HUMANITEC_ORG }}
          HUMANITEC_CONTEXT: /orgs/${{ secrets.HUMANITEC_ORG }}
          HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
        run: |
            cd .github/workflows/bin
            humctl delete env pr-${{ github.event.number }}
