name: Pull Request
on:
  pull_request:
    paths:
      - 'samples/onlineboutique/frontend/**'
      - '.github/workflows/ob-frontend-pr.yaml'
    types:
      - closed
jobs:
  ob-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete Humanitec Env
        run: |
          export HUMANITEC_ORG=${{ secrets.HUMANITEC_ORG }}
          export HUMANITEC_TOKEN=${{ secrets.HUMANITEC_TOKEN }}
            
          .github/workflows/bin/humctl delete env pr-${{ github.event.number }} \
              --context /orgs/${HUMANITEC_ORG}
