name: Pull Request
on:
  pull_request:
    paths:
      - 'samples/onlineboutique/frontend/**'
      - '.github/workflows/ob-frontend-pr.yaml'
    types:
      - closed
jobs:
  ob-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - name: checkout humctl bin
        uses: actions/checkout@v3
      - name: delete humanitec env
        run: |
          .github/workflows/bin/humctl delete env pr-${{ github.event.number }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --context /orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}
