name: Pull Request
on:
  pull_request:
    paths:
      - 'samples/onlineboutique/frontend/**'
      - '.github/workflows/ob-frontend-pr.yaml'
    types:
      - closed
jobs:
  ob-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Humanitec Env
        run: |
            curl -X DELETE \
            -H "Content-Type: application/json" \
            -H 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}/envs/pr-${{ github.event.number }}
